#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/ocaml/xlreg_ml
  
  blListGen \
    -d ../xlreg_ml \
    -1L  \
    -u $DVCZ_UDIR \
    -X .ssh \
    $@
  
else
  echo "DEV_BASE is not defined"
fi
